### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by hfiguiere** [fxbox/users#56]
Various test fail intermittently.

**Comment by ferjm** [comment]
Did you try running them as mentioned in https://github.com/fxbox/users#rust-tests ?

**Comment by hfiguiere** [comment]
we shouldn't have to. that's what I'm talking about.

**Comment by ferjm** [comment]
That requires some refactoring. I believe @delapuente looked into that at some point.

**Comment by hfiguiere** [comment]
I do have a patch anyway. Will submit a PR

**Comment by hfiguiere** [comment]
Merged.
