### ISSUE TITLE
Use bcrypt for storing passwords

### ISSUE THREAD

**Issue by jedireza** [fxbox/users#58]
MD5 is not sufficient. Let's use bcrypt instead.

**Comment by jedireza** [comment]
FYI: The crate we're using, [`rust-crypto`](https://github.com/DaGenix/rust-crypto/), supports this.

**Comment by hfiguiere** [comment]
"support" with air quotes.

**Comment by hfiguiere** [comment]
but there is the crate `pwhash` that should provide what is need, and it uses `rust-crypto`.

**Comment by jedireza** [comment]
@hfiguiere I'm not sure what you mean by:

> "support" with air quotes.

I didn't dig into it myself, but the list of supported algorithms included bcrypt. Does it not actually do bcrypt hashing? Are there known issues with this crate?

Also, we're using `rust-crypto` in [`foxbox/src/stable_uuid.rs`](https://github.com/fxbox/foxbox/blob/5b1435d4a3149d6cda55296b3036f3a13176a6ca/src/stable_uuid.rs). If there is an issue with this crate we should call it out in that repo too.

**Comment by hfiguiere** [comment]
crate is fine as it does what is mostly advertised and documented (this is a very weak point of that crate). As mentioned above `pwhash` is a crate that does what we want, that uses `rust-crypto` as an crypto implementation.

I'm about to submit a PR that implement bcrypt() as password hashing.

**Comment by hfiguiere** [comment]
Just to clarify what I said earlier in better terms. `rust-crypto` supports bcrypt as a cypher. `pwhash` implements password hashing using, amongst other things, `bcrypt` as implemented by `rust-crypto`, following the standard hash format.

**Comment by ferjm** [comment]
Closed by #71
