### ISSUE TITLE
Support secure browser resources

### ISSUE THREAD

**Issue by azasypkin** [fxbox/users#68]
Eg. we may want to _securely_ download videos/snapshots/other_media from foxbox using plain `a[download]` links.

**Comment by azasypkin** [comment]
@ferjm ping :)

**Comment by fabricedesre** [comment]
If this is only for https://github.com/fxbox/foxbox/pull/189 we don't need that either.

**Comment by azasypkin** [comment]
What about video/photo/any_other_resource to download. Eg. via `a[download]` or do-all-the -things-over-xhr?

**Comment by fabricedesre** [comment]
Sure, but your first comment is about _streaming_. So maybe a more complete description would help?

**Comment by azasypkin** [comment]
It was just one example, but here we are with updated description :)

**Comment by azasypkin** [comment]
One more current usecase is `get` command of ip camera adapter that returns JPEG image content directly that I'd like to use as `img.src`.

**Comment by ferjm** [comment]
Closed by #69
